import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { paginate } from "../src/helpers/paginate";
import Pagination from "../src/components/Pagination";
import styles from "../styles/Home.module.css";

export default function Home({ data }: any) {
  const [currentPage, setCurrentPage] = useState(1);
  const pageSize = 10;

  const paginatedPosts = paginate(data, currentPage, pageSize);

  const onPageChange = (page: number) => {
    setCurrentPage(page);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h3>
        <strong>NextJS x Pagination</strong>
      </h3>

      {paginatedPosts.map((item: any) => {
        return (
          <div className={styles.post} key={item.id}>
            {item.title}
          </div>
        );
      })}

      <Pagination
        items={data.length} // 100
        currentPage={currentPage} // 1
        pageSize={pageSize} // 10
        onPageChange={onPageChange}
      />
    </div>
  );
}

export const getStaticProps = async () => {
  const res = await fetch("https://jsonplaceholder.typicode.com/todos");
  const data = await res.json();

  return {
    props: { data },
  };
};
